apiVersion: v1
kind: Service
metadata:
  name: app
spec:
  selector:
    app: app
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 80
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  selector:
    matchLabels:
      app: app
  replicas: 1
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: app
        image: opeco17/django-template/app
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3031
        env:
        - name: TZ
          valueFrom:
            configMapKeyRef:
                name: general-config
                key: tz
        - name: DJANGO_SETTINGS_MODULE
          value: config.settings.production
      - name: app-nginx
        image: opeco17/django-template/nginx:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        env:
        - name: UWSGI_PASS
          value: "localhost:3031"
        - name: SERVER_PORT
          value: "80"
        - name: TZ
          valueFrom:
            configMapKeyRef:
                name: general-config
                key: tz