apiVersion: v1
kind: Service
metadata:
  name: mysite
spec:
  selector:
    app: mysite
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 80
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysite
spec:
  selector:
    matchLabels:
      app: mysite
  replicas: 1
  template:
    metadata:
      labels:
        app: mysite
    spec:
      containers:
      - name: mysite
        image: opeco17/django-template/mysite
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3031
        env:
        - name: TZ
          valueFrom:
            configMapKeyRef:
                name: general-config
                key: tz
      - name: mysite-nginx
        image: opeco17/django-template/nginx:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        env:
        - name: UWSGI_PASS
          value: "localhost:3031"
        - name: SERVER_PORT
          value: "80"
        - name: PROJECT_NAME
          value: mysite
        - name: TZ
          valueFrom:
            configMapKeyRef:
                name: general-config
                key: tz